config/routes.rb
VotaPrato::Application.routes.draw do
  resources :qualificacaos

  resources :clientes

  resources :comentarios
  resources :restaurantes
  match 'inicio' => 'restaurantes#index'
  match ':controller(/:action(/:id(.:format)))'

  resources :restaurantes do
    resources :qualificacaes
  end

  match 'rack',
    :to => proc{|env| [200, {"Content-Type" => "text/html"}, ["App Rack numa rota Rails<br/>Rodrigo Martins"]]}

end

app/models/qualificacao.rb
class Qualificacao < ActiveRecord::Base
  validates_presence_of :nota, :message => " - deve ser preenchido"
  validates_presence_of :valor_gasto, :message => " - deve ser preenchido"
  validates_numericality_of :nota,
                            :greater_than_or_equal_to => 0,
                            :less_than_or_equal_to => 10,
                            :message => " - deve ser um numero entre 0 e 10"
  validates_numericality_of :valor_gasto,
                            :greater_than => 0,
                            :message => " - deve ser um numero maior que 0"

  belongs_to  :cliente
  belongs_to  :restaurante
  
  has_many :comentarios, :as => :comentavel

  validates_presence_of :cliente_id, :restaurante_id
  validates_associated :cliente, :restaurante

end

app/controllers/qualificacaos_controller.rb
class QualificacaosController < ApplicationController
  # GET /qualificacaos
  # GET /qualificacaos.xml
  def index
    @qualificacaos = Qualificacao.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @qualificacaos }
    end
  end

  # GET /qualificacaos/1
  # GET /qualificacaos/1.xml
  def show
    @qualificacao = Qualificacao.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @qualificacao }
    end
  end

  # GET /qualificacaos/new
  # GET /qualificacaos/new.xml
  def new
    @qualificacao = Qualificacao.new

   if params[:cliente]
	@qualificacao.cliente = Cliente.find(params[:cliente])
   end
   if params[:restaurante]
 	@qualificacao.restaurante = Restaurante.find(params[:restaurante])
   end

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @qualificacao }
    end
  end

  # GET /qualificacaos/1/edit
  def edit
    @qualificacao = Qualificacao.find(params[:id])
  end

  # POST /qualificacaos
  # POST /qualificacaos.xml
  def create
    @qualificacao = Qualificacao.new(params[:qualificacao])

    respond_to do |format|
      if @qualificacao.save
        format.html { redirect_to(@qualificacao, :notice => 'Qualificacao was successfully created.') }
        format.xml  { render :xml => @qualificacao, :status => :created, :location => @qualificacao }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @qualificacao.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /qualificacaos/1
  # PUT /qualificacaos/1.xml
  def update
    @qualificacao = Qualificacao.find(params[:id])

    respond_to do |format|
      if @qualificacao.update_attributes(params[:qualificacao])
        format.html { redirect_to(@qualificacao, :notice => 'Qualificacao was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @qualificacao.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /qualificacaos/1
  # DELETE /qualificacaos/1.xml
  def destroy
    @qualificacao = Qualificacao.find(params[:id])
    @qualificacao.destroy

    respond_to do |format|
      format.html { redirect_to(qualificacaos_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/qualificacaos_helper.rb
module QualificacaosHelper
end

app/views/qualificacaos/_form.html.erb
<%= form_for(@qualificacao) do |f| %>
  <% if @qualificacao.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@qualificacao.errors.count, "error") %> prohibited this qualificacao from being saved:</h2>

      <ul>
      <% @qualificacao.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
	<% if @qualificacao.cliente %>
		<%= f.hidden_field 'cliente_id' %>
	<% else %>
		<p><%= f.label :cliente_id %><br />
		<%= f.collection_select(:cliente_id,
			Cliente.order('nome'),
			:id, :nome, {:prompt => true}) %></p>
	<% end %>
  </div>
  <div class="field">
	<% if @qualificacao.restaurante %>
		<%= f.hidden_field 'restaurante_id' %>
	<% else %>
		<p><%= f.label :restaurante_id %><br />
		<%= f.collection_select(:restaurante_id,
			Restaurante.order('nome'),
			:id, :nome, {:prompt => true}) %></p>
	<% end %>
  </div>
  <div class="field">
    <%= f.label :nota %><br />
    <%= f.text_field :nota %>
  </div>
  <div class="field">
    <%= f.label :valor_gasto %><br />
    <%= f.text_field :valor_gasto %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/qualificacaos/_novo_comentario.html.erb
<div id='novo_comentario'>
	<a href="#" onclick="$('#novo_comentario').children().toggle();">Novo comentario</a>
	<div id="form_comentario" style="display: none;">
		<%= form_for Comentario.new, :remote => true do |f| %>
				<%= hidden_field :comentario, :comentavel_id, :value => comentavel.id %>
				<%= hidden_field :comentario, :comentavel_type, :value => comentavel.class %>
			<div class="field">
				<%= f.label 'conteudo' %><br />
				<%= f.text_area 'conteudo' %>
			</div>
			<div class="actions">
				<%= f.submit %>
				<a href="#" onclick="$('#novo_comentario').children().toggle();">Cancelar</a>
			</div>
		<% end %>
	</div>
</div>
<%content_for :js do%>
	$('#form_comentario').bind('ajax:complete', function(xhr, result){
	$('#comentarios').html(result.responseText);
	$('#form_comentario textarea').val("")
	$('#form_comentario').hide();
	$('#novo_comentario > a').show();
	});
<%end%>

app/views/qualificacaos/edit.html.erb
<h1>Editing qualificacao</h1>

<%= render 'form' %>

<%= link_to 'Show', @qualificacao %> |
<%= link_to 'Back', qualificacaos_path %>

app/views/qualificacaos/index.html.erb
<h1>Listing qualificacaos</h1>

<table>
  <tr>
    <th>Cliente</th>
    <th>Restaurante</th>
    <th>Nota</th>
    <th>Valor gasto</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @qualificacaos.each do |qualificacao| %>
  <tr>
    <td><%= qualificacao.cliente.nome %></td>
    <td><%= qualificacao.restaurante.nome %></td>
    <td><%= qualificacao.nota %></td>
    <td><%= valor_formatado(qualificacao.valor_gasto) %></td>
    <td><%= link_to 'Show', qualificacao %></td>
    <td><%= link_to 'Edit', edit_qualificacao_path(qualificacao) %></td>
    <td><%= link_to 'Destroy', qualificacao, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Qualificacao', new_qualificacao_path %>

app/views/qualificacaos/new.html.erb
<h1>New qualificacao</h1>

<%= render 'form' %>

<%= link_to 'Back', qualificacaos_path %>

app/views/qualificacaos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Cliente:</b>
  <!-- @qualificacao.cliente_id -->
  <%= @qualificacao.cliente.nome %>
</p>

<p>
  <b>Restaurante:</b>
  <%= @qualificacao.restaurante.nome %>
</p>

<p>
  <b>Nota:</b>
  <%= @qualificacao.nota %>
</p>

<p>
  <b>Valor gasto:</b>
  <%= valor_formatado(@qualificacao.valor_gasto) %>
</p>

<%= link_to 'Edit', edit_qualificacao_path(@qualificacao) %> |
<%= link_to 'Back', qualificacaos_path %>

<br/>
<% unless @qualificacao.restaurante.comentarios.empty?  %>
  <%= comentarios @qualificacao.restaurante %>
<% end %>

<%= novo_comentario(@qualificacao.restaurante) %>